name: CI Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Vlad Krivulets"
      GROUP_NUMBER: "M3112"

    steps:
    - name: Display personal info
      run: |
        echo "Full Name: ${{ env.FULL_NAME }}"
        echo "Group Number: ${{ env.GROUP_NUMBER }}"
        echo "GitHub Username: ${{ github.actor }}"

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.0.0
        pip install pytest==7.4.0

    - name: Lint code with flake8
      run: |
        flake8 .

    - name: Run unit tests
      run: |
        pytest tests/
