name: CI Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Vlad Krivulets"
      GROUP_NUMBER: "M3112"

    steps:
    - name: Display personal info
      run: |
        echo "Full Name: ${{ env.FULL_NAME }}"
        echo "Group Number: ${{ env.GROUP_NUMBER }}"
        echo "GitHub Username: ${{ github.actor }}"


    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r ../requirements.txt

    - name: Lint code with flake8
      run: |
        flake8 .

    - name: Run unit tests with pytest
      run: |
        pytest tests/

    - name: Check coverage
      run: |
        pytest --cov-report term-missing --cov=./src tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
